# roboteq_constants.py 
# By: Nathan Adkins 
# WVU IRL

'''
Roboteq User Manual: https://www.roboteq.com/docman-list/motor-controllers-documents-and-files/documentation/user-manual/272-roboteq-controllers-user-manual-v21/file

Runtime Commands                              page 188  
DS402 Runtime Commands                        page 209  
Runtime Queries                               page 222  
DS402 Runtime Queries                         page 268  
Query History Commands                        page 286  
Maintenance Commands                          page 289  
General Configuration and Safety              page 296  
Analog, Digital, Pulse IO Configurations      page 312  
Motor Configurations                          page 330  
Brushless Secific Commands                    page 364  
AC Induction Specific Commands                page 385  
CAN Communication Commands                    page 391  
TCP Communication Commands                    page 397
'''

AC_INDUCTION_SPECIFIC_COMMANDS = {
 'AC Induction Operating Mode': 'BFBK',
 'Mutual Inductance': 'ILM',
 'Rotor Leakage Inductance': 'ILLR',
 'Rotor Resistance': 'IRR',
 'Minimum Power': 'MPW',
 'Optimal Slip Frequency': 'MXS',
 'Rotor': 'RFC',
 'Induction': 'VPH Channel Ratio'
   }

ANALOG_DIGITAL_PULSE_CONFIG = {
 'Analog Input Center (0)': 'ACTR',
 'Analog Input Deadband': 'ADB',
 'Analog Input Use': 'AINA',
 'Analog Input Linearity': 'ALIN',
 'Analog Input Max': 'AMAX',
 'Analog Input Action at Max': 'AMAXA',
 'Analog Input Min': 'AMIN',
 'Analog Input Action at Min': 'AMINA',
 'Analog Conversion Type': 'AMOD',
 'Analog Input Conversion Polarity': 'APOL',
 'Digital Input Action': 'DINA',
 'Digital Input Active Level': 'DINL',
 'Digital Output Action': 'DOA',
 'Digital Outputs Active Level': 'DOL',
 'Pulse Input Center': 'PCTR',
 'Pulse Input Deadband': 'PDB',
 'Pulse Input Use': 'PINA',
 'Pulse Input Linearity': 'PLIN',
 'Pulse Input Max': 'PMAX',
 'Pulse Input Action at Max': 'PMAXA',
 'Pulse Input Min': 'PMIN',
 'Pulse Input Action at Min': 'PMINA',
 'Pulse Input Capture Type': 'PMOD',
 'Pulse Input Capture Polarity': 'PPOL'
   }

BRUSHLESS_SPECIFIC_COMMANDS = {
 'Brushless Angle Zero Adjust': 'BADJ',
 'Brushless timing angle adjust': 'BADV',
 'BEMF Coupling Constant': 'BECC',
 'Brushless Sinusoidal Angle Sensor': 'BFBK',
 'Brushless Internal Sensor Max Limit': 'BHL',
 'Brushless Internal Sensor Action at Max': 'BHLA',
 'Brushless Internal Sensor Home Count': 'BHOME',
 'Brushless Internal Sensor Min Limit': 'BLL',
 'Brushless Internal Sensor Action at Min': 'BLLA',
 'Brushless Switching Mode': 'BMOD',
 'Number of pole pairs': 'BPOL',
 'Brushless Reference Seek Power': 'BZPW',
 'Hall Sensor Position Type': 'HPO',
 'Hall Sensor Angle Table': 'HSAT',
 'Hall Sensor Map': 'HSM',
 'Current PID Integral Gain': 'KIF',
 'Current PID Proportional Gain': 'KPF',
 'D-axis motor Inductance': 'LD',
 'Q-axis motor Inductance': 'LQ',
 'Phase Shift Angle': 'PSA',
 'Motor Stator Resistance': 'RS',
 'SinCos/SSI Sensor Poles': 'SPOL',
 'Sensorless Start-Up Frequency': 'SSF',
 'BEMF Integrator Limit': 'SVT',
 'Swap Windings': 'SWD',
 'FOC Target Id': 'TID',
 'Motor Voltage constant': 'VK',
 'Cos Amplitude': 'ZSMA',
 'SinCos Calibration': 'ZSMC'
   }

CAN_COMMANDS = {
 'CANOpen Auto start': 'CAS',
 'CAN Bit Rate': 'CBR',
 'CAN Mode': 'CEN',
 'CAN Heartbeat': 'CHB',
 'CAN Consumer Heartbeat Lost Action': 'CHLA',
 'CAN Listen Node ID': 'CLSN',
 'CAN Node ID': 'CNOD',
 'MiniCAN SendRate': 'CSRT',
 'CANOpen TPDO SendRate': 'CTPS',
 'CANOpen Transmission Type': 'CTT',
 'DS402 FSA': 'FSA'
   }

DS402_RUNTIME_COMMANDS = {
 'Control Word (DS402)': 'CW',
 'Following Error Window (DS402)': 'FEW',
 'Following Error Time Out (DS402)': 'FET',
 'Interpolation Time Period (DS402)': 'INT',
 'Max Motor Speed (DS402)': 'MSL',
 'Profile Acceleration (DS402)': 'PAC',
 'Profile Deceleration (DS402)': 'PDC',
 'Software Position Limit (DS402)': 'PLT',
 'Target Position (DS402)': 'POS',
 'Profile Velocity (DS402)': 'PSP',
 'Modes of Operation (DS402)': 'ROM',
 'Target Velocity (DS402)': 'SPE',
 'Velocity Acceleration (DS402)': 'SAC',
 'Velocity Deceleration (DS402)': 'SDC',
 'Target Profile Velocity (DS402)': 'SPC',
 'Velocity Min/Max Amount (DS402)': 'SPL',
 'Target Torque (DS402)': 'TC',
 'Torque Slope (DS402)': 'TSL'
   }

DS402_RUNTIME_QUERIES = {
 'Modes of Operation Display (DS402)': 'AOM',
 'Control Word (DS402)': 'CW',
 'Velocity Actual Value (DS402)': 'SPE',
 'Following Error Window (DS402)': 'FEW',
 'Following Error Time Out (DS402)': 'FET',
 'Interpolation Time Period (DS402)': 'INT',
 'Max Motor Speed (DS402)': 'MSL',
 'Profile Acceleration (DS402)': 'PAC',
 'Profile Deceleration (DS402)': 'PDC',
 'Software Position Limit (DS402)': 'PLT',
 'Target Position (DS402)': 'POS',
 'Profile Velocity (DS402)': 'PSP',
 'Position Actual Value (DS402)': 'PST',
 'Velocity Demand (DS402)': 'RMP',
 'Modes of Operation (DS402)': 'ROM',
 'Target Velocity (DS402)': 'S16',
 'Velocity Acceleration (DS402)': 'SAC',
 'Velocity Deceleration (DS402)': 'SDC',
 'Supported Drive Modes (DS402)': 'SDM',
 'Target Profile Velocity (DS402)': 'SPC',
 'Velocity Min/Max Amount (DS402)': 'SPL',
 'Status Word (DS402)': 'SW',
 'Target Torque (DS402)': 'TC',
 'Torque Actual Value (DS402)': 'TRQ',
 'Torque Slope (DS402)': 'TSL',
 'Velocity Demand Value (DS402)': 'VDV',
 'Velocity Sensor Actual Value (DS402)': 'VSA',
 'Version Number (DS402)': 'VNM'
   }

GENERAL_CONFIG_SAFETY = {
 'Analog Center Command to Start': 'ACS',
 'Analog keep within Guard Bands': 'AMS',
 'User Storage in Battery Backed RAM': 'BEE',
 'Script Auto-Start': 'BRUN',
 'Linearity Command Linearity': 'CLIN',
 'Command Priorities': 'CPRI',
 'Default Command value': 'DFC',
 'Modbus Mode': 'DMOD',
 'Enable/Disable Serial Echo': 'ECHOF',
 'User-Defined Values': 'EE',
 'Raw Redirect Mode': 'ISM',
 'Modbus Data Alignment': 'MDAL',
 'Modbus Slave ID': 'MNOD',
 'Pulse keep within Min & Max Safety': 'PMS',
 'Enable RS485': 'RS485',
 'Set RS232/RS485 baudrate': 'RSBR',
 'Serial Data Watchdog': 'RWD',
 'Select Print output port for scripting': 'SCRO',
 'Spektrum Center': 'SKCTR',
 'Spektrum Deadband': 'SKDB',
 'Spektrum Linearity': 'SKLIN',
 'Spektrum Max': 'SKMAX',
 'Spektrum Min': 'SKMIN',
 'Assign Spektrum port to motor command': 'SKUSE',
 'Safe Torque Off': 'STO',
 'Telemetry string': 'TELS'
   }

MAINTENANCE_COMMANDS = {
 'Motor/Sensor Setup': 'CLMOD',
 'Reset configuration to factory defaults': 'CLRST',
 'Save calibrations to Flash': 'CLSAV',
 'Update Firmware via USB': 'DFU',
 'Load Parameters from EEPROM': 'EELD',
 'Dump Flash Log Data': 'EELOG',
 'Reset Factory Defaults': 'EERST',
 'Save Configuration in EEPROM': 'EESAV',
 'Erase Flash Log Data': 'ERASE',
 'Lock Configuration Access': 'LK',
 'Reset Controller': 'RESET',
 'Script Load': 'SLD',
 'Set Time': 'STIME',
 'Unlock Configuration Access': 'UK'
   }

MOTOR_CONFIG = {
 'Amps Limit': 'ALIM',
 'Amps Trigger Action': 'ATGA',
 'Amps Trigger Delay': 'ATGD',
 'Amps Trigger Level': 'ATRIG',
 'Brake Delay': 'BKD',
 'Bypass Trajectory/Ramp': 'BPR',
 'Brake Release Voltage': 'BRV',
 'Brake Hold Voltage': 'BHV',
 'Brake Delay Time': 'BDT',
 'Closed Loop Feedback Sensor': 'BLFB',
 'Stall Detection': 'BLSTD',
 'Close Loop Error Detection': 'CLERD',
 'Motor Fault Deceleration Rate': 'EDEC',
 'Encoder Max Limit': 'EHL',
 'Encoder Action at Max': 'EHLA',
 'Encoder Home Count': 'EHOME',
 'Encoder Min Limit': 'ELL',
 'Encoder Action at Min': 'ELLA',
 'Encoder Usage': 'EMOD',
 'Encoder Pulse/Rev Value': 'EPPR',
 'PID Integrator Limit': 'ICAP',
 'PID Differential Gain': 'KDG',
 'PID Integral Gain': 'KIG',
 'PID Proportional Gain': 'KPG',
 'Motor Acceleration Rate': 'MAC',
 'Motor Deceleration Rate': 'MDEC',
 'Molex Input': 'MLX',
 'Operating Mode': 'MMOD',
 'Min Speed RPM Value': 'MNRPM',
 'Position Mode Velocity': 'MVEL',
 'Mixed Mode': 'MXMD',
 'Motor Max Power Forward': 'MXPF',
 'Motor Max Power Reverse': 'MXPR',
 'Max Speed RPM': 'MXRPM',
 'Position Turns Min to Max': 'MXTRN',
 'Overvoltage hysteresis': 'OVH',
 'Overvoltage Limit': 'OVL',
 'Over Temperature Limit': 'OTL',
 'SSI Sensor Resolution': 'SCPR',
 'Sensor Error Detection': 'SED',
 'SSI Sensor Max Limit': 'SHL',
 'SSI Sensor Action at Max': 'SHLA',
 'SSI Sensor Home Count': 'SHOME',
 'SSI Sensor Min Limit': 'SLL',
 'SSI Sensor Action at Min': 'SLLA',
 'SSI Sensor Usage': 'SMOD',
 'Motor Torque Constant': 'TNM',
 'Undervoltage Limit': 'UVL'
   }

RUNTIME_COMMANDS = {
 'Set Acceleration': 'AC',
 'Next Acceleration': 'AX',
 'Boolean Variable': 'B',
 'Spectrum Bind': 'BND',
 'Set Encoder Counters': 'C',
 'Set Brushless Counter': 'CB',
 'Set Motor Command via CAN': 'CG',
 'CAN Send': 'CS',
 'Set SSI Sensor Counter': 'CSS',
 'Raw Redirect Send': 'CU',
 'Reset Individual Digital Out bits': 'D0',
 'Set Individual Digital Out bits': 'D1',
 'Set Deceleration': 'DC',
 'Set all Digital Out bits': 'DS',
 'Next Decceleration': 'DX',
 'Save Confguration in EEPROM': 'EES',
 'Emergency Shutdown': 'EX',
 'Go to Speed or to Relative Position': 'G',
 'Go to Torque Amps': 'GIQ',
 'Go to Flux Amps': 'GID',
 'Load Home counter': 'H',
 'Emergency Stop Release': 'MG',
 'Stop in all modes': 'MS',
 'Go to Absolute Desired Position': 'P',
 'Go to Relative Desired Position': 'PR',
 'Next Go to Relative Desired Position': 'PRX',
 'Next Go to Absolute Desired Position': 'PX',
 'MicroBasic Run': 'R',
 'Set Pulse Out': 'RC',
 'Set Motor Speed': 'S',
 'Safety Stop': 'SFT',
 'STO Self-Test': 'STT',
 'Next Velocity': 'SX',
 'Set User Variable': 'VAR'
   }

RUNTIME_QUERIES = {
 'Read Motor Amps': 'A',
 'Read Analog Inputs': 'AI',
 'Read Analog Input after Conversion': 'AIC',
 'Read Rotor Angle': 'ANG',
 'Read Raw Sin/Cos sensor': 'ASI',
 'Read User Boolean Variable': 'B',
 'Read Battery Amps': 'BA',
 'Read Brushless Count Relative': 'BCR',
 'Read BL Motor Speed in RPM': 'BS',
 'Read Battery State of Charge in percentage': 'BSC',
 'Read BL Motor Speed as 1/1000 of Max RPM': 'BSR',
 'Read Battery State Of Charge in AmpHours': 'BMC',
 'Read BMS Status Flags': 'BMF',
 'Read BMS Switch States': 'BMS',
 'Read Encoder Counter Absolute': 'C',
 'Read Raw CAN frame': 'CAN',
 'Read Absolute Brushless Counter': 'CB',
 'Read Raw Redirect Received Frames Count': 'CD',
 'Read Raw CAN Received Frames Count': 'CF',
 'CAN Consumer Heartbeat Status': 'CHS',
 'Read Converted Analog Command': 'CIA',
 'Read Internal Pulse Command': 'CIP',
 'Read Internal Serial Command': 'CIS',
 'Read RoboCAN Alive Nodes Map': 'CL',
 'Read Encoder Count Relative': 'CR',
 'Read Relative SSI Sensor Counter': 'CSR',
 'Read Absolute SSI Sensor Counter': 'CSS',
 'Read Digital Inputs': 'D',
 'Read Individual Digital Inputs': 'DI',
 'Read Raw Redirect Received Frame': 'DDT',
 'Read Digital Output Status': 'DO',
 'Read Motor DC/Peak Amps': 'DPA',
 'Read Destination Reached': 'DR',
 'Read Closed Loop Error': 'E',
 'Read Feedback': 'F',
 'Read FOC Angle Adjust': 'FC',
 'Read Flow Sensor Counter': 'FLW',
 'Read Fault Flags': 'FF',
 'Read Firmware ID': 'FID',
 'Read Firmware ID (numerical)': 'FIN',
 'Read Runtime Status Flag': 'FM',
 'Read Status Flags': 'FS',
 'Read Hall Sensor States': 'HS',
 'Is RoboCAN Node Alive': 'ICL',
 'Read Spektrum Receiver': 'K',
 'Read Lock status': 'LK',
 'Read Motor Command Applied': 'M',
 'Read Field Oriented Control Motor Amps': 'MA',
 'Read Magsensor Track Detect': 'MGD',
 'Read Magsensor Markers': 'MGM',
 'Read Magsensor Status': 'MGS',
 'Read Magsensor Track Position': 'MGT',
 'Read Magsensor Gyroscope': 'MGY',
 'Read MagSensor Tape Cross Detection': 'MGX',
 'Read Motor Power Output Applied': 'P',
 'Read Phase Amps': 'PHA',
 'Read Pulse Inputs': 'PI',
 'Read Pulse Input after Conversion': 'PIC',
 'Read Encoder Motor Speed in RPM': 'S',
 'Read Script Checksum': 'SCC',
 'Read Sensor Errors': 'SEC',
 'Read Raw Redirect Received Frame as string': 'SDT',
 'Read Sensor Angle': 'SNA',
 'Read Encoder Speed Relative': 'SR',
 'Read SSI Sensor Motor Speed in RPM': 'SS',
 'Read SSI Sensor Speed Relative': 'SSR',
 'Indication STO Self-Test Result': 'STT',
 'Read Temperature': 'T',
 'Read Time': 'TM',
 'Read Position Relative Tracking': 'TR',
 'Read Control Unit type and Controller Model': 'TRN',
 'Read MCU Id': 'UID',
 'Read Volts': 'V',
 'Read User Integer Variable': 'VAR'
   }

TCP_COMMANDS = {
 'Enable DHCP': 'DHCP',
 'Gateway Address': 'GWA',
 'IP Address': 'IPA',
 'IP Port': 'IPP',
 'Primary DNS': 'PDNS',
 'Subnet Mask': 'SBM',
 'Secondary DNS': 'SDNS',
 'TCP Mode': 'WMOD'
   }

